import { SidebarProvider } from '@/components/ui/sidebar';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import './globals.css';

import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <SidebarProvider
          defaultOpen={false}
          style={
            {
              '--sidebar-width': '15rem',
              '--sidebar-width-mobile': '15rem',
            } as React.CSSProperties
          }
        >
          {children}
        </SidebarProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
